# fly.toml app configuration file generated for aged-snowflake-2596 on 2023-10-18T22:58:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aged-snowflake-2596"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
